dbt_project:
  outputs:
    prod:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: CHEMIST_WAREHOUSE
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 4
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: ENGINEERING_WH
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: CHEMIST_WAREHOUSE
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      schema: "{{ env_var('SNOWFLAKE_USER') }}"
      threads: 4
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: ENGINEERING_WH
  target: "{{ env_var('DBT_ENV') }}"
